### ISSUE TITLE
Toast on hide transition issue when bottom positioned

### ISSUE THREAD

**Issue by tamirhal** [StratusCode/react-native-toast-hook#14]
Hey. I'm trying to use this library and I have some issues with the transition on hiding.
looks like this hiding transition of the bottom position is going up instead of going down
 
(when I'm using react-native-toast-message which this library is based on there is none of this issue)

react-native 0.64.1
react-navigation/native 5.9.4

My App.js

```
        <ToastProvider>
          <NavigationContainer theme={{ colors: { background: bgColor } }} linking={deepLinksHandler}>
            {...}
          </NavigationContainer>
        </ToastProvider>
```

![toast](https://user-images.githubusercontent.com/43725711/120176680-3f2b4e00-c210-11eb-9da2-6fa275ab7e09.gif)

**Comment by caleb-harrelson** [comment]
Thanks for pointing this out. We missed it as we only use the top animation. I'll look into it soon.
